name: Build and Test

on:
  workflow_call:
    inputs:
      nuget_username:
        required: true
        type: string
      solution_file:
        required: true
        type: string
    secrets:
      nuget_read_token:
        required: true
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        env:
          NUGET_PASSWORD: ${{ secrets.nuget_read_token }}
          NUGET_USERNAME: ${{ inputs.nuget_username }}
        run: dotnet restore ${{ inputs.solution_file }} /p:GITHUB_ACTIONS=true

      - name: Build
        run: dotnet build ${{ inputs.solution_file }} --configuration Release --no-restore /p:GITHUB_ACTIONS=true

      - name: Test
        run: dotnet test ${{ inputs.solution_file }} --configuration Release --no-build --verbosity normal
